export const gameState = {
    points: 0,
    gameOver: false,
    isPaused: false,

    particles: [],
    enemies: [],
    orbitBalls: [],
    spawnCount: 0,
    targetAngle: 0,
    difficultyRamp: 0,
    gameSpeed: 1,
    player2: null,

    wave: 1,
    inBossFight: false,
    enemiesKilledThisWave: 0,
    enemiesToNextBoss: 30,

    bossLevel: 0,
    prestigeCount: 0,
    postPrestigeUnlocked: false,

    playerHP: 3,
    maxHP: 3,
    damageFlash: 0,

    waveTransitionTimer: 0,
    waveTransitionDuration: 180,
    killStreak: 0,
    maxKillStreak: 0,
    backgroundEvolution: 0,
    currentPalette: 0,
    unlockedPalettes: [0],
    bossIntroTimer: 0,
    bossIntroDuration: 120,
    lastDamageTime: 0,
    lastKillStreakMilestone: 0,
    transitionState: "playing",

    pierceLevel: 0,
    cryoLevel: 0,
    cryoRadius: 0,
    cryoSlow: 1,
    gravityLevel: 0,
    multiLevel: 0,
    novaLevel: 0,
    novaCooldown: 0,
    novaMaxCooldown: 8000,
    novaRadius: 150,
    novaDamage: 1,
    novaFlash: 0,
    regenLevel: 0,
    regenTimer: 0,
    regenInterval: 15000,

    overchargeLevel: 0,
    fortressLevel: 0,
    vortexLevel: 0,
    chainLevel: 0,
    hyperLevel: 0,
    starfireLevel: 0,
    orbitDamageBoost: 0,
    pierceRange: 200,
    pulseArmorLevel: 0,
    pulseArmorTimer: 0,
    pulseArmorInterval: 7000,
    pulseArmorRadius: 90,
    pulseArmorDamage: 0,
    riftMineLevel: 0,
    mineSpawnTimer: 0,
    mineSpawnInterval: 9000,
    mineRadius: 70,
    mineDamage: 1,
    bloodNovaLevel: 0,
    freezeShatterLevel: 0,
    orbitEchoLevel: 0,
    orbitEchoSpawnTimer: 0,
    phaseShieldLevel: 0,
    phaseShieldReady: false,
    phaseShieldCooldownTimer: 0,
    centerInvulnTimer: 0,
    mines: [],
    orbitEchoes: [],

    lastFrameTime: 0,
    offsetX: 0,
    offsetY: 0,
    isDraggingTree: false,
    lastX: 0,
    lastY: 0,
    scale: 1,
    dragMoved: false,
    shakeTime: 0,

    mouse: { x: null, y: null },
    touchActive: false,

    audioCtx: null,
    masterGain: null,
    audioStarted: false,
    reverbNode: null,

    laserCooldown: 0,
    laserFireDelay: 5000,
    laserDamage: 0.25,

    shieldLevel: 0,
    shieldRadius: 60,
    shieldBounce: 4,
    shieldDamage: 0,
    shieldPulseTime: 0,
    shieldBounceCooldown: 20000,
    shieldBounceTimer: 0,

    magnetLevel: 0,
    magnetStrength: 0.04,

    savedPoints: 0,
    restartAfterMenu: false,

    activeLaserBeams: [],
    player: null,
    prestigeStars: 0,
    savedPoints: 0,
    restartAfterMenu: false,

    difficultyMode: 'normal',
    diffSpawnMul: 1,
    diffSpeedMul: 1
};

export const refs = {
    canvas: null,
    ctx: null,
    infoDiv: null,
    glass: null,
    orb: null,
    closeGlass: null,
    prestigeGlass: null,
    prestigeOrbEl: null,
    prestigeResetBtn: null,
    speedBtn: null,
    paletteBtn: null,
    upgradeNodes: [],
    pOrbit: null,
    pSpeed: null,
    pRadius: null,
    zoomLevelEl: null,
    difficultyMenu: null,
    customCols: null,
    customRows: null,
    waveProgress: null
};
